#ifndef __PARSER_STATE_CPP
#define __PARSER_STATE_CPP
enum class ParserState { 
PARSER_INITIAL_STATE,
PARSER_READING_COMMAND, 
PARSER_READING_PARAMETERS, 
PARSER_WAITING_TERMINATION,
PARSER_READING_ARRAY,
PARSER_WAITING_COMMENT,
PARSER_LONG_COMMENT,
PARSER_COMMENT };
#endif
