#ifndef __EVENT_TYPE_HPP
#define __EVENT_TYPE_HPP
enum class EventType { 
  CLEAR_BUFFER, 
  COPY_BUFFER_TO_COMMAND, 
  COPY_BUFFER_TO_PARAMETER, 
  EXECUTE, 
  IGNORE_LINE, IGNORE, IGNORE_END
};
#endif
