#ifndef __MACHINE_STATE_CPP
#define __MACHINE_STATE_CPP
enum class MachineState : int { 
PREVIOUS_STATE,
INITIAL_STATE,
READING_COMMAND, 
READING_PARAMETERS, 
WAITING_TERMINATION,
READING_ARRAY,
WAITING_COMMENT,
LONG_COMMENT,
COMMENT, 
LONG_COMMENT_WAITING_TERMINATION
};
#endif
